export enum ErrorCode {
  // Auth
  RATE_LIMITED = 'RATE_LIMITED',
  MISSING_TOKEN = 'MISSING_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  PLATFORM_MISMATCH = 'PLATFORM_MISMATCH',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  WRONG_PASSWORD = 'WRONG_PASSWORD',
  REFRESH_TOKEN_REUSE_DETECTED = 'REFRESH_TOKEN_REUSE_DETECTED',

  // User state
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ACCOUNT_DEACTIVATED = 'ACCOUNT_DEACTIVATED',
  ACCESS_SUSPENDED = 'ACCESS_SUSPENDED',

  // Resource lookups
  ADMIN_NOT_FOUND = 'ADMIN_NOT_FOUND',
  STAFF_NOT_FOUND = 'STAFF_NOT_FOUND',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_IN_USE = 'ROLE_IN_USE',
  ROLE_NAME_ALREADY_EXISTS = 'ROLE_NAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',

  // Inventory
  SIZE_NOT_FOUND = 'SIZE_NOT_FOUND',
  FINISH_NOT_FOUND = 'FINISH_NOT_FOUND',
  SERIES_NOT_FOUND = 'SERIES_NOT_FOUND',
  DESIGN_NOT_FOUND = 'DESIGN_NOT_FOUND',
  SIZE_FINISH_NOT_FOUND = 'SIZE_FINISH_NOT_FOUND',
  SERIES_SIZE_FINISH_NOT_FOUND = 'SERIES_SIZE_FINISH_NOT_FOUND',
  DUPLICATE_NAME = 'DUPLICATE_NAME',
  DUPLICATE_MAPPING = 'DUPLICATE_MAPPING',
  RESOURCE_IN_USE = 'RESOURCE_IN_USE',

  // Authorization
  SUPER_ADMIN_REQUIRED = 'SUPER_ADMIN_REQUIRED',
  SUPER_ADMIN_PROTECTED = 'SUPER_ADMIN_PROTECTED',

  // Validation
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  PASSWORD_TOO_WEAK = 'PASSWORD_TOO_WEAK',

  // Routing
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',

  // System
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
